### ISSUE TITLE
cudatest failed(cu.init return Unknown error)

### ISSUE THREAD

**Issue by oskca** [chewxy/cu#2]
With the error:
```
panic: Unknown

goroutine 1 [running]:
github.com/chewxy/cu.init.1()
	github.com/chewxy/cu/cu.go:13 +0x5e
github.com/chewxy/cu.init()
	github.com/chewxy/cu/_obj/_cgo_import.go:87 +0x11d
main.init()
	github.com/chewxy/cu/cmd/cudatest/main.go:27 +0x49
```

Go: 1.8
nvidia-smi -i 0 output:
```
...
NVIDIA-SMI 375.26                 Driver Version: 375.26
...
```

**Comment by chewxy** [comment]
Can you check if you have CUDA installed?

```
nvcc --version
```

**Comment by oskca** [comment]
`nvcc --version` output:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```

It seems that I havn't do `modprobe nvidia_uvm`, after this and reboot, this problem is gone :smile:

**Comment by chewxy** [comment]
Thanks for the update. I should probably add that into the documentation as well
